name: PermissionSystem
main: me.phantomclone.permissionsystem.PermissionSystemPlugin
author: PhantomClone
version: ${version}
description: PlayLegend applicant task
api-version: 1.21.1
depend:
  - ProtocolLib
commands:
  language:
  permission:
  rank:
